dependencies:
  plugins/gitfast:
    repo: felipec/git-completion
    branch: master
    version: tag:v2.1
    postcopy: |
      set -e
      rm -rf git-completion.plugin.zsh Makefile t tools
      mv README.adoc MANUAL.adoc
      mv -f src/* .
      rmdir src
  plugins/history-substring-search:
    repo: zsh-users/zsh-history-substring-search
    branch: master
    version: 87ce96b1862928d84b1afe7c173316614b30e301
    precopy: |
      set -e
      rm -f zsh-history-substring-search.plugin.zsh
      test -e zsh-history-substring-search.zsh && mv zsh-history-substring-search.zsh history-substring-search.zsh
    postcopy: |
      set -e
      test -e dependencies/OMZ-README.md && cat dependencies/OMZ-README.md >> README.md
  plugins/gradle:
    repo: gradle/gradle-completion
    branch: master
    version: ea018400d86610d0f79f84debbb33c2d2ef5dbec
    precopy: |
      set -e
      find . ! -name _gradle -delete
